include:
  - template: Terraform/Base.latest.gitlab-ci.yml
  - template: Jobs/SAST-IaC.latest.gitlab-ci.yml

stages:
  - init
  - validate
  - test
  - build
  - deploy
  - cleanup

variables:
  TF_DATA_DIR: "$HOME/.terraform"
  IGNORE_TF_DEPRECATION_WARNING: "true"
  SECURE_ANALYZERS_PREFIX: "ccr.ccs.tencentyun.com/gitlab-org"
  TF_STATE_BASE_ADDRESS: $CI_API_V4_URL/projects/$CI_PROJECT_ID/terraform/state

image:
  name: "registry.cn-hangzhou.aliyuncs.com/goldenimage/terragrunt:1.10.1-v0.69.9"

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - ${TF_ROOT}/**/.terraform
  policy: pull

before_script:
  - cp /etc/gitlab-runner/certs/gitlab.home.local.crt /usr/local/share/ca-certificates/ca.crt
  - update-ca-certificates
  - |-
    cat <<EOF > ~/.terraformrc
    provider_installation {
      network_mirror {
        url = "https://obs.home.local/mirror/"
      }
    }
    EOF

fmt:
  extends: .terraform:fmt
  script: 
    - terragrunt hclfmt -check -diff
    - terragrunt run-all fmt -check -diff -recursive

init:
  stage: init
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .terraform/
    policy: pull-push
  script:
    - terragrunt run-all init -input=false -reconfigure --terragrunt-parallelism 1 -lockfile=readonly

validate:
  extends: .terraform:validate
  script: 
    - terragrunt run-all validate

build:
  extends: .terraform:build
  script: 
    - terragrunt run-all plan -input=false -out=plan.cache
    - terragrunt run-all show -json plan.cache | jq -r "${JQ_PLAN}" | jq -s 'map(to_entries) | flatten | group_by(.key) | map({(.[0].key):map(.value) | add}) | add' > "${TF_ROOT}/plan.json"
  artifacts:
    paths:
      - ${TF_ROOT}/**/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

deploy:
  extends: .terraform:deploy
  dependencies: [build]
  script:
    - terragrunt run-all apply --terragrunt-non-interactive -input=false plan.cache
  rules:
    - if: $CI_COMMIT_TITLE == "deploy"
      when: manual

destroy:
  extends: .terraform:destroy
  script:
    - terragrunt run-all destroy --terragrunt-non-interactive -input=false
  rules:
    - if: $CI_COMMIT_TITLE == "destroy"
      when: manual